FROM nginx
EXPOSE 10000

RUN apt-get -y install nginx

# Copy all config files
COPY ./docker/nginx_conf/webfrontend-dev.conf /etc/nginx/conf.d/webfrontend.conf
COPY ./docker/nginx_conf/admin-dev.conf /etc/nginx/conf.d/admin.conf
COPY ./docker/nginx_conf/nginx.conf /etc/nginx/nginx.conf
