FROM nginx
EXPOSE 10000

# RUN apt-get -y install openssl

# openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

# Copy all config files
COPY ./docker/nginx_conf/webfrontend-prod.conf /etc/nginx/conf.d/webfrontend.conf
COPY ./docker/nginx_conf/nginx.conf /etc/nginx/nginx.conf
# COPY ./docker/nginx_conf/server.crt /etc/nginx/server.crt
# COPY ./docker/nginx_conf/server.key /etc/nginx/server.key
# COPY ./docker/nginx_conf/ssl-params.conf /etc/nginx/ssl-params.conf

# Uses the volume that contains the current project files
ENV NODE_DEV /usr/src/app-dev
RUN mkdir -p $NODE_DEV
